repository_type: pipeline

nf_core_version: 3.3.1

lint:
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .prettierrc.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-orfology_logo_light.png
    - docs/images/nf-core-orfology_logo_light.png
    - docs/images/nf-core-orfology_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-orfology_logo_light.png
    - docs/images/nf-core-orfology_logo_light.png
    - docs/images/nf-core-orfology_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: tcdo
  name: ORFology
  description: protein annotation based on sequence composition
  author: Asher Preska Steinberg
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: false
